## YAML Template.
language: java
addons:
    sonarcloud:
        organization: "ninojairo-github"
        token:
            secure: GBRDg1Uf1Bqn0kTLy1XVDKLOie+VvRT3mRzH/5Szz81Ek+jBs4FjUueyig9NZqoTNad18RkioNcawlV5nhO2N8Vy4+xa6WPYqqqPJ1ViisJzOuSZk5W1NvkDpiTCXYIi6w4WgLypUapeD/jTUb2tIqQNNlh5R2zy9GG8/CEYvf6FgFM541tVpzvMvTJ3mTWMo84ouLgSQ6lAWjaHdwpJ6xNYYQMRq79LptYrTczo8F9HPY0TwzYJQxboHkPzTersUnlLbyiK/XAsjLHkSjVvdgtqEw14hSbH9VHqVoB63ZPSfE8h1SlGwcpBNu0aD31Wpyd6BC5KMFTdNHfuiZRIzCGV7h2+2sQ05sDnCYmajh4m2gS0sl6UtEu9BHdUKSjfjLMCzFcpVxzG/ZQJKoCx88d6xAl29IL1W9m79nWkDN48DjW3y8Wd6fXaPTjVXRW+1rnP95xN47cdJveiykWr3tPbTEz5EwS6EMZgKLGEtMH21Jw0GYqHKHlVBnfuvtUKrqOmhQVRKRBKkOc8aPoVnBG927/SuA9uCB+hlD9EdhmPGBV4ECt83iGKz73hhjYf9pYhLGsAXx6HdLrtGhQqn07Eq178p9Y8BVmGJuy6jRC/MNRZihKjJhli9+cVgRLO6oQC7lYcqVx7vb8lu4pFD3uDRdTtaqZ0pxGAcKTtVA0=
script:
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
---
